---
services:
    api-tools:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: jpcorrect-api-tools
        environment:
            YAHOO_API_KEY: ${YAHOO_API_KEY}
            X_API_KEY: ${API_TOOLS_KEY}
            ALLOW_ORIGINS: ${API_TOOLS_ALLOW_ORIGINS:-*}
            ALLOWED_HOSTS: ${API_TOOLS_ALLOWED_HOSTS:-*}
        ports:
            - "127.0.0.1:${API_TOOLS_PORT:-8000}:8000"
        restart: unless-stopped
